name: Release
on:
  release:
    types: [published]
env:
  PROJECT: "github.com/kelindar/talaria"
  GO111MODULE: "on"
  
jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, windows/386, windows/amd64, darwin/386, darwin/amd64 
        goos: [linux, windows, darwin]
        goarch: ["386", amd64]
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}

  publish:
    name: Publish Docker
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
      - name: Build the tagged Docker image
        run: |
          go build .
          docker build . --file Dockerfile --build-arg GO_BINARY=talaria --tag kelindar/talaria:${{steps.vars.outputs.tag}}
      - name: Push the tagged Docker image
        run: docker push kelindar/talaria:${{steps.vars.outputs.tag}}
      - name: Build the latest Docker image
        run: docker build . --file Dockerfile --tag kelindar/talaria:latest
      - name: Push the latest Docker image
        run: docker push kelindar/talaria:latest