name: Go
on: [push]
env:
  PROJECT: "github.com/kelindar/talaria"
  GO111MODULE: "on"

jobs:

  test:
    name: Tests and Coverage
    runs-on: macos-latest
    steps:

    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Run tests
      run: |
        go test -race ./...